# Generated by Django 4.2 on 2025-03-02 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0007_alter_mouvement_causal_alter_tarif_causal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='date_paye',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
