# Generated by Django 5.2.5 on 2025-08-25 09:43

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nom', models.CharField(max_length=100)),
                ('nom_bref', models.CharField(default='', max_length=10)),
                ('date_initiale', models.DateField(blank=True, null=True)),
                ('date_finale', models.DateField(blank=True, null=True)),
                ('actuel', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('nom_du_referent', models.CharField(max_length=100)),
                ('prenom_du_referent', models.CharField(max_length=100)),
                ('email_du_referent', models.CharField(max_length=100)),
                ('telephone_du_referent', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('externe', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nom', models.CharField(max_length=34)),
                ('prenom', models.CharField(max_length=34)),
                ('date_enquete', models.DateField(blank=True, null=True)),
                ('condition_eleve', models.CharField(choices=[('CONF', 'CONF'), ('ABAN', 'ABAN'), ('PROP', 'PROP'), ('TBD', 'TBD')], max_length=4)),
                ('sex', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('cs_py', models.CharField(choices=[('C', 'CS'), ('E', 'EXTRA'), ('P', 'PY'), ('A', 'ACC'), ('B', 'BRAVO')], default='C', max_length=7)),
                ('hand', models.CharField(blank=True, choices=[('DA', 'DA'), ('DM', 'DM'), ('DL', 'DL'), ('DV', 'DV'), ('DP', 'DP'), ('TL', 'TL')], max_length=2, null=True)),
                ('annee_inscr', models.SmallIntegerField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_parent', models.CharField(blank=True, max_length=100, null=True)),
                ('note_eleve', models.TextField(blank=True, default='-', null=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Eleve',
                'verbose_name_plural': 'Eleves',
            },
        ),
        migrations.CreateModel(
            name='TypeClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('type_ecole', models.CharField(choices=[('M', 'MATERNELLE'), ('P', 'PRIMAIRE'), ('S', 'SECONDAIRE'), ('L', 'LYCEE')], db_index=True, max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nom', models.CharField(max_length=30)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.ecole')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.typeclasse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_uniformes', models.IntegerField(default=0)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.anneescolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scuelo.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='scuelo.eleve')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scuelo.eleve')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniformReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('student_type', models.CharField(choices=[('C', 'CS'), ('E', 'EXTRA'), ('P', 'PY'), ('A', 'ACC'), ('B', 'BRAVO')], editable=False, max_length=2)),
                ('quantity', models.PositiveIntegerField(default=2)),
                ('cost_per_uniform', models.DecimalField(decimal_places=2, help_text='Cost of each uniform', max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('delivered', 'Delivered'), ('paid', 'Paid')], default='reserved', max_length=10)),
                ('date_reserved', models.DateField(default=django.utils.timezone.now)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_reservations', to='scuelo.anneescolaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_reservations', to='scuelo.eleve')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang1', models.PositiveIntegerField(blank=True, help_text='Rank 1', null=True)),
                ('rang2', models.PositiveIntegerField(blank=True, help_text='Rank 2', null=True)),
                ('rang3', models.PositiveIntegerField(blank=True, help_text='Rank 3', null=True)),
                ('rang_annuelle', models.PositiveIntegerField(blank=True, help_text='Annual Rank', null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangs', to='scuelo.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangs', to='scuelo.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangs', to='scuelo.eleve')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Rangs',
                'unique_together': {('eleve', 'classe', 'annee_scolaire')},
            },
        ),
    ]
