# Generated by Django 4.2.13 on 2024-05-27 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_bref', models.CharField(default='', max_length=10)),
                ('date_initiale', models.DateField(blank=True)),
                ('date_finale', models.DateField(blank=True)),
                ('actuel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecole', models.CharField(choices=[('M', 'MATERNELLE'), ('P', 'PRIMAIRE')], db_index=True, max_length=1)),
                ('nom', models.CharField(max_length=10)),
                ('ordre', models.IntegerField(blank=True, null=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=34)),
                ('prenom', models.CharField(max_length=34)),
                ('date_enquete', models.DateField(blank=True, null=True)),
                ('condition_eleve', models.CharField(choices=[('CONF', 'CONF'), ('ABAN', 'ABAN'), ('PROP', 'PROP')], max_length=4)),
                ('sex', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('cs_py', models.CharField(choices=[('C', 'CS'), ('E', 'EXTRA'), ('P', 'PY'), ('A', 'ACC'), ('B', 'BRAVO')], default='C', max_length=7)),
                ('hand', models.CharField(blank=True, choices=[('DA', 'DA'), ('DM', 'DM'), ('DL', 'DL'), ('DV', 'DV')], max_length=2, null=True)),
                ('annee_inscr', models.SmallIntegerField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_parent', models.CharField(blank=True, max_length=100, null=True)),
                ('note_eleve', models.TextField(blank=True, default='-', null=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Eleve',
                'verbose_name_plural': 'Eleves',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.anneescolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scuelo.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causal', models.CharField(choices=[('INS', 'Inscription'), ('SCO', 'Scolarite'), ('TEN', 'Tenue'), ('CAN', 'Cantine')], db_index=True, max_length=5)),
                ('montant', models.PositiveBigIntegerField()),
                ('date_paye', models.DateField(db_index=True, default='')),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scuelo.inscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paye'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.eleve')),
            ],
            options={
                'unique_together': {('date', 'student')},
            },
        ),
    ]
