# Generated by Django 4.2.16 on 2024-10-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvement',
            name='destination',
        ),
    ]
