# Generated by Django 4.2.15 on 2024-09-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='tranche_1_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='tranche_1_montant',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='tranche_2_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='tranche_2_montant',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='tranche_3_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='tranche_3_montant',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
