# Generated by Django 4.2.13 on 2024-08-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='condition_eleve',
            field=models.CharField(choices=[('CONF', 'CONF'), ('ABAN', 'ABAN'), ('PROP', 'PROP'), ('TBD', 'TBD')], max_length=4),
        ),
    ]
