# Generated by Django 4.2.15 on 2024-09-08 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0002_tarif_tranche_1_due_date_tarif_tranche_1_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='scuelo.classe'),
        ),
    ]
