# Generated by Django 4.2.13 on 2024-08-18 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0003_studentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='tarif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scuelo.tarif'),
        ),
    ]
