# Generated by Django 4.2.15 on 2024-09-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0003_alter_tarif_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='tranche_1_due_date',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='tranche_1_montant',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='tranche_2_due_date',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='tranche_2_montant',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='tranche_3_due_date',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='tranche_3_montant',
        ),
        migrations.AlterField(
            model_name='tarif',
            name='date_expiration',
            field=models.DateField(verbose_name="Date d'expiration or tranche dates"),
        ),
    ]
