# Generated by Django 4.2.15 on 2024-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0004_remove_tarif_tranche_1_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneescolaire',
            name='date_finale',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='date_initiale',
            field=models.DateField(blank=True, null=True),
        ),
    ]
