# Generated by Django 4.2 on 2025-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0004_alter_eleve_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
