# Generated by Django 4.2 on 2025-04-19 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0005_alter_classe_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang1', models.PositiveIntegerField(blank=True, help_text='Rank 1', null=True)),
                ('rang2', models.PositiveIntegerField(blank=True, help_text='Rank 2', null=True)),
                ('rang3', models.PositiveIntegerField(blank=True, help_text='Rank 3', null=True)),
                ('rang_annuelle', models.PositiveIntegerField(blank=True, help_text='Annual Rank', null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangs', to='scuelo.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangs', to='scuelo.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangs', to='scuelo.eleve')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Rangs',
                'unique_together': {('eleve', 'classe', 'annee_scolaire')},
            },
        ),
    ]
