# Generated by Django 4.2.15 on 2024-09-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0005_alter_anneescolaire_date_finale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='causal',
            field=models.CharField(blank=True, choices=[('INS', 'Inscription'), ('SCO1', 'Scolarite 1'), ('SCO2', 'Scolarite 2'), ('SCO3', 'Scolarite 3'), ('TEN', 'Tenue'), ('CAN', 'Cantine')], db_index=True, max_length=5, null=True),
        ),
    ]
